# app/config/routing.yml
my_app_user:
    resource: "@MyAppUserBundle/Resources/config/routing.yml"
    prefix:   /

  
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@MyAppUserBundle/Resources/config/routing/all.xml"

fos_facebook_channel:
    resource: "@FOSFacebookBundle/Resources/config/routing.xml"
    
    
admin_login:
    pattern:  /admin/login
    defaults: { _controller: FOSUserBundle:Security:login }

admin_check:
    pattern:  /admin/login_check
    defaults: { _controller: FOSUserBundle:Security:check }

admin_logout:
    pattern:  /admin/logout
    defaults: { _controller: FOSUserBundle:Security:logout }